### PR TITLE
some cleanup of comment section

### PR DESCRIPTION
**Pull request by pelletier2017**
Did some refactoring changing some redundancy. Added function print_and_log() since there was typically print("text") followed by logging.info(<strtime> + "text"). This way the text is printed to console and time+text is logged.

Next step is to break apart process_comments() and get some cleaner error handling that closes things out.

### CODE REVIEW

**Comment by HadManySons** [comment]
Don't bother with the process_comments() part just yet. What I'm working on with the regex won't merge vary well with any changes in that. After I commit the update, then it would be safe to do so. In fact, I wouldn't do anything else, because I'm changing a lot of stuff that is going to generate a lot of conflicts. I would hold off until after I publish the update.

**Comment by HadManySons** [comment]
Why the multi-line edit? This breaks the max line length PEP-8 rule: https://www.python.org/dev/peps/pep-0008/#maximum-line-length
edit: Unless I'm missing something

**Review by HadManySons — DISMISSED** [review]
I like this, much cleaner.

**Comment by pelletier2017** [comment]
Reason for the multi-line edit was me not realizing pycharm draws the line at 120 not 80.

**Comment by HadManySons** [comment]
Just chance those to PEP-8 compliant lines and I can pull it all in

**Comment by pelletier2017** [comment]
Theres 1 or 2 that are just over 80 char, theyre the SQL that would look pretty bad to break up. Eventually we will be able to reduce the indent to make things cleaner. I changed pycharm to show line at 80 char for future use haha.

**Review by HadManySons — APPROVED** [review]
Looks good

**Pull request merged**
