### PR TITLE
Update process_comment.py

### PR DESCRIPTION
**Pull request by aethros**
Regexp changes

### CODE REVIEW

**Comment by CyberAustin** [comment]
How did you test this? I'm getting:

```Traceback (most recent call last):

  File "/app/main.py", line 7, in <module>
    from process_comment import generate_reply, send_reply

  File "/app/process_comment.py", line 220
    if dict_type == "officer":

IndentationError: unexpected indent```

**Comment by HadManySons** [comment]
Were you able to test this at all? Because it is throwing indentation errors that I can't seem to fix.

```Traceback (most recent call last):
  File "/app/main.py", line 7, in <module>
    from process_comment import generate_reply, send_reply
  File "/app/process_comment.py", line 220
    if dict_type == "officer":
IndentationError: unexpected indent

**Comment by aethros** [comment]
Didn't see this error. I'll fix and resubmit!

**Comment by HadManySons** [comment]
Any update?

**Comment by HadManySons** [comment]
Nothing heard. Closing this.

**Pull request closed without merging**
