### PR TITLE
refactoring process_comments to manageable size functions

### PR DESCRIPTION
**Pull request by pelletier2017**
Split up process comments a little bit with process_enlisted() and process_officer(). Going to keep chopping away until the functions are reasonable size and easy to test. I am running it every time i make a change so I will do my best to not cause any bugs. Once its done being refactored i'll add the tests and verify I havn't caused any new bugs and everything is working as it should.

### CODE REVIEW

**Comment by pelletier2017** [comment]
This next set of commits does quite a bit. It breaks apart the main file into a few files of different concerns. afsc_bot (aka main), setup_bot, read_csv_files, and process_comment. 400 lines was quite a bit and they cover different things so I think the splitup helps reduce complexity by allowing you to ignore how the bot is setup, dicts are made etc.

I also refactored the 8 lists into 2 dictionaries: full_afsc_dict and prefix_dict.

full afsc dict ->
..............................enlisted -->
....................................................base_afsc
....................................................job_title
....................................................shred (if it exists)
................................officer -->
....................................................base_afsc
....................................................job_title
....................................................shred (if it exists)

prefix_dict -->
................................enlisted -->
....................................................prefix_char
....................................................prefix_title
................................officer -->
....................................................prefix_char
....................................................prefix_title

**Comment by pelletier2017** [comment]
Finished a bunch of unit tests, just run process_comment to see them. I'll eventually import them into the file so they dont take up too much space.

**Comment by HadManySons** [comment]
@pelletier2017 As the code is in this form, the bot doesn't include the shred if there's a skill level in the AFSC (2A5X3A vs 2A573A example post https://www.reddit.com/r/AFSCbot/comments/6m4vea/asdfasdf/)

The current running version of this does not suffer this issue

**Comment by pelletier2017** [comment]
Here everything should be ready to merge. Please check to make sure i didn't break anything! It now ignores hyperlinks, allows punctuation at the end of the afsc, Theres tests for both enlisted and officer regex. 

I didn't yet test that everything works perfectly with things like 1W051, 1W0X1, K1W051 all being in the same comment, but currently if the bot would print the same thing for two AFSC, it won't repeat itself.

New feature is it adds a link if there is a page on the /r/airforce wiki.

**Review by HadManySons — APPROVED** [review]
Works.

**Pull request merged**
